version: '3.3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    network_mode: "host"
    ports:
      - "5601:5601"